### ISSUE TITLE
load model error, checkpoint['name'] is dataparallel

### ISSUE THREAD

**Issue by leixiang90** [samuelschen/DSB2018#2]
Loading checkpoint './checkpoint/300.pkl'
Traceback (most recent call last):
  File "valid.py", line 499, in <module>
    main(args.ckpt, args.csv, args.save, args.mask, args.dataset, args.iou)
  File "valid.py", line 27, in main
    model = load_ckpt(filepath=fn)
  File "/home/leixiang/disk/work/MICCAI_2018_cell_seg/codes/DSB2018-master/helper.py", line 241, in load_ckpt
    model.load_state_dict(checkpoint['model'])
  File "/home/leixiang/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CaUNet:
	Missing key(s) in state_dict: "c1.block1.conv.weight", "c1.block1.conv.bias",

**Comment by leixiang90** [comment]
I have 2 GPUs, when it is run on 2 GPUs, the error came up, but when it is run on only one GPU, there is no error...
